name: Vanilla Desktop Nvidia
id: nvidia
vibversion: 1.1.0

stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:dev
  addincludes: true
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends
  cleanup:
    - /var/cache/apt/pkgcache.bin
    - /var/cache/apt/srcpkgcache.bin
    - /var/cache/debconf
    - /var/cache/fontconfig
    - /var/cache/ldconfig
    - /var/cache/man
    - /var/log/*

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt-get update

  - name: install-nvidia
    type: apt
    sources:
      - packages:
        - nvidia-driver
        - nvidia-vaapi-driver
        - nvidia-settings
        - nvidia-smi
        - firmware-misc-nonfree
    cleanup:
      - /var/lib/dkms/mok.key

  - name: nvidia-sysd-units
    type: shell
    commands:
    - mkdir -p /etc/systemd/system/systemd-suspend.service.wants
    - mkdir -p /etc/systemd/system/systemd-hibernate.service.wants
    - ln -s /usr/lib/systemd/system/nvidia-suspend.service /etc/systemd/system/systemd-suspend.service.wants/nvidia-suspend.service || true
    - ln -s /usr/lib/systemd/system/nvidia-hibernate.service /etc/systemd/system/systemd-hibernate.service.wants/nvidia-hibernate.service || true
    - ln -s /usr/lib/systemd/system/nvidia-resume.service /etc/systemd/system/systemd-hibernate.service.wants/nvidia-resume.service || true

  - name: extra-utilities
    type: apt
    sources:
      - packages:
        - switcheroo-control

  - name: vanilla-tools
    type: shell
    sources:
      - type: tar
        url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.1/vanilla-tools-amd64.tar.gz
        checksum: aef32f07820e0993e534e6bccfa1a6daae6c8c6f0543d3e073f4f121f2ef2e31
        only-arches: [amd64]
      - type: tar
        url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.1/vanilla-tools-arm64.tar.gz
        checksum: e59b098338de6f6071376e07ec79b17be6c8f0a0dd354fab128e1e86a36d0862
        only-arches: [arm64]
    commands:
    - mkdir -p /usr/bin
    - cp /sources/vanilla-tools/vanilla-tools*/vanilla-tools/nrun /usr/bin/nrun
    - cp /sources/vanilla-tools/vanilla-tools*/vanilla-tools/prime-switch /usr/bin/prime-switch
    - chmod +x /usr/bin/nrun
    - chmod +x /usr/bin/prime-switch

  - name: enable-wayland
    type: shell
    commands:
    - mkdir -p /etc/udev/rules.d
    - ln -s /dev/null /etc/udev/rules.d/61-gdm.rules

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - apt remove -y zutty gnome-shell-extension-prefs
    - SUDO_FORCE_REMOVE=yes apt purge -y sudo
    - lpkg --lock
