name: Vanilla Desktop Nvidia
id: nvidia
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt-get update

  - name: install-nvidia
    type: apt
    source:
      packages:
      - nvidia-driver
      - nvidia-vaapi-driver
      - nvidia-settings
      - nvidia-smi
      - firmware-misc-nonfree

  - name: nvidia-sysd-units
    type: shell
    commands:
    - mkdir -p /etc/systemd/system/systemd-suspend.service.wants
    - mkdir -p /etc/systemd/system/systemd-hibernate.service.wants
    - ln -s /usr/lib/systemd/system/nvidia-suspend.service /etc/systemd/system/systemd-suspend.service.wants/nvidia-suspend.service || true
    - ln -s /usr/lib/systemd/system/nvidia-hibernate.service /etc/systemd/system/systemd-hibernate.service.wants/nvidia-hibernate.service || true
    - ln -s /usr/lib/systemd/system/nvidia-resume.service /etc/systemd/system/systemd-hibernate.service.wants/nvidia-resume.service || true

  - name: extra-utilities
    type: apt
    source:
      packages:
      - switcheroo-control

  - name: vanilla-tools
    type: shell
    source:
      type: tar
      url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
      checksum: 0e1d92d9c9154f9a115e97b40ff692afa52ddd0d9f770a8ec67440bf1a48aa72
    commands:
    - mkdir -p /usr/bin
    - cp /sources/vanilla-tools/vanilla-tools/nrun /usr/bin/nrun
    - cp /sources/vanilla-tools/vanilla-tools/prime-switch /usr/bin/prime-switch
    - chmod +x /usr/bin/nrun
    - chmod +x /usr/bin/prime-switch

  - name: enable-wayland
    type: shell
    commands:
    - mkdir -p /etc/udev/rules.d
    - ln -s /dev/null /etc/udev/rules.d/61-gdm.rules

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - apt remove -y zutty gnome-shell-extension-prefs
    - SUDO_FORCE_REMOVE=yes apt purge -y sudo
    - lpkg --lock

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard 
          - rm -f ./minisign.pub ./minisign.key 
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
