#!/bin/bash

url=$(jq -r '.registry + "/" + .name + ":" + .tag' /etc/abroot/abroot.json)
if [ $url = "ghcr.io/vanilla-os/nvidia:main" ]; then
	abroot rebase ghcr.io/vanilla-os/gnome-nvidia:latest --rebase-only
fi
